import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav"; // Import Nav component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
          <Nav /> {/* Add Nav component */}
          <main className="flex-grow bg-gray-50">
            <div className="min-h-[calc(100vh-5rem-5rem)]"> {/* Revert to inline height calculation */}
              {children}
            </div>
          </main>
          <footer className="bg-gray-800 text-white text-center py-4">
            <p>&copy; 2025 ChknTndr. All rights reserved. Site by Jeremy@WithJeremy.com</p>
          </footer>
      </body>
    </html>
  );
}
